blank_issues_enabled: false
contact_links:
  - name: Start a Discussion
    url: https://github.com/agcloud69/shoppyfit-tool/discussions
    about: Questions, rough ideas, or rather unprecise feature requests go here.
